# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
before:
  hooks:
    - sh -c 'which buf > /dev/null 2>&1 || go install github.com/bufbuild/buf/cmd/buf@latest'
    - go mod download
    - sh -c 'cd internal/proto && buf generate'
builds:
  - id: hi
    main: ./cmd/hi
    binary: hi
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commit={{ .ShortCommit }}
      - -X github.com/jimschubert/hi/internal/daemon.daemonVersion={{ .Version }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - formats:
      - tar.gz
    files:
      - LICENSE
      - README.md
sboms:
  - id: archive
    artifacts: archive
checksum:
  name_template: checksums.txt
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^chore'
      - '^test'
      - '^wip'
docker_digest:
  name_template: "digests.txt"
#dockers_v2:
#  - images:
#      - "jimschubert/hi
#    tags:
#      - "latest"
#      - "{{ .Tag }}"
#      - "v{{ .Major }}.{{ .Minor }}"
#      - "v{{ .Major }}"
#    dockerfile: release.Dockerfile
#    labels:
#      "org.opencontainers.image.created": "{{ .Date }}"
#      "org.opencontainers.image.name": "{{ .ProjectName }}"
#      "org.opencontainers.image.revision": "{{ .FullCommit }}"
#      "org.opencontainers.image.version": "{{ .Version }}"
#      "org.opencontainers.image.source": "https://github.com/jimschubert/hi"
#      "org.opencontainers.image.licenses": "Apache-2.0"
#    build_args:
#      APP_NAME: "{{ .ProjectName }}"
